# This file is generated by the template.

REGISTRY	?=lcr.loongnix.cn
ORGANIZATION	?=library
REPOSITORY	?=buildkit
TAG		?=0.12.3-alpine3.21
LATEST		?=true

IMAGE=$(REGISTRY)/$(ORGANIZATION)/$(REPOSITORY):$(TAG)
LATEST_IMAGE=$(REGISTRY)/$(ORGANIZATION)/$(REPOSITORY):latest
GIT_URL=https://github.com/Loongson-Cloud-Community/buildkit.git

default: image


image:
	docker build -t lcr.loongnix.cn/library/buildkit:0.12.3-alpine3.21 --build-arg https_proxy=$(https_proxy) --build-arg BUILDPLATFORM=linux/loong64 .
push:
	docker push lcr.loongnix.cn/library/buildkit:0.12.3-alpine3.21
